---
Name: searchlist
After: 'framework/*','cms/*'
---
DataObject:
  extensions:
    - Marcz\Search\Extensions\SearchDataListener
ContentController:
  extensions:
    - Marcz\Search\Extensions\SearchContentExtension
Marcz\Search\Processor\Exporter:
  extensions:
    - Marcz\Search\Extensions\SafeguardMember
