---
Name: searchlist
---
DataObject:
  extensions:
    - Marcz\Search\Extensions\SearchDataListener
ContentController:
  extensions:
    - Marcz\Search\Extensions\SearchContentExtension
SiteTree:
  extensions:
    - Marcz\Search\Extenstions\SearchListSiteTree
Marcz\Search\Processor\Exporter:
  extensions:
    - Marcz\Search\Extensions\SafeguardMember
